version: '3'
services:
 express-server:
  build:
    context: ./
    dockerfile: Dockerfile.express
  ports:
    - '3000:3000'
 angular-app:
  build:
    context: ./
    dockerfile: Dockerfile.angular
  ports:
    - '80:80'
 mysql-db:
  build: 
    context: ./
    dockerfile: Dockerfile.mysql
  ports:
    - '3306:3306'
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_PASS}
    MYSQL_DATABASE: ${MYSQL_DATABASE}