version: '3'
services:
 express-server:
  build:
    context: ./
    dockerfile: Dockerfile.express
  ports:
    - '3000:3000'
  depends_on:
    mysql-db:
      condition: service_started
  environment:
    DB_USER: 'root'
    DB_PASS: 'P4ssw0rt34_*'
    DB_NAME: 'mydb'
    MYSQL_DATABASE: 'mydb'
 angular-app:
  build:
    context: ./
    dockerfile: Dockerfile.angular
  ports:
    - '4200:4200'
  depends_on:
    - mysql-db
 mysql-db:
  build: 
    context: ./
    dockerfile: Dockerfile.mysql
    args:
      DB_PASS: P4ssw0rt34_*
  environment:
    MYSQL_ROOT_PASSWORD: 'P4ssw0rt34_*'
    MYSQL_DATABASE: 'mydb'
  healthcheck:
    test: ["CMD", "mysqladmin", "-u", "root", "-pP4ssw0rt34_*", "ping"]
    timeout: 200s
    retries: 20


