# Crea la Angular app
ARG NODE_VERSION=18.18.0

FROM node:${NODE_VERSION}-alpine as build

WORKDIR /app

COPY . .

# Dependencies Install
RUN yarn --frozen-lockfile

RUN yarn build

# Serve de la application
EXPOSE 4200

CMD ["yarn", "start"]

  