FROM mysql:5.7
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=P4ssw0rt34_*

# Copiael archivo SQL en la Docker image
COPY ./SQL/db_grupo9.sql /docker-entrypoint-initdb.d/

# Run del SQL file cuando corre el container
RUN ["chmod", "+x", "/docker-entrypoint-initdb.d/db_grupo9.sql"]


