  # Crea la Angular app
  FROM node:18.18.0 AS build

  WORKDIR /app

  COPY package*.json ./
  RUN npm install
  COPY . .

  RUN npm run build

  # Serve de la application
  FROM nginx:1.17.1-alpine
  COPY --from=build /app/dist /usr/share/nginx/html
  EXPOSE 80
  CMD ["nginx", "-g", "daemon off;"]

  